template_path: eb_bridgepf.yaml
stack_name: bridgepf-uat
parameters:
  AwsDefaultVpcId: vpc-9c70bbf9
  AwsSnsBounceNotificationEndpoint: bridgepf-uat-bounce-notifications@sagebase.org
  DNSHostname: bridgepf-uat
  ElastiCacheInstanceType:  cache.t2.micro
  Server2EC2SecurityGroup: sg-07acc18067a1eaf71
  Server2EndpointUrl: bridgeserver2-uat.sagebridge.org
  VpcSubnetIds: subnet-2ec6ee06, subnet-e2197187, subnet-3a47a84d, subnet-9095259c, subnet-133c3455, subnet-42b1d178
