project_code: sage-bionetworks
profile: {{ var.profile | default("default") }}
region: {{ var.region }}
template_bucket_name: {{ environment_variable.BridgeInfraCfBucket_uat }}
template_key_prefix: {{ environment_variable.TRAVIS_BRANCH | default("testing") }}
