#This template is used to setup dynamo resources.  Dynamo is shared
#across environments therefore this template only needs to be created once.
#
#Usage:
#  aws --profile bridge.admin --region us-east-1 \                                                                                               develop ◼
#  cloudformation create-stack \
#  --stack-name dynamo \
#  --on-failure DELETE \
#  --capabilities CAPABILITY_NAMED_IAM \
#  --template-body file://cf_templates/dynamo.yml
Description: Setup Dyanmo resources
AWSTemplateFormatVersion: 2010-09-09
Resources:
  AWSSNSDynamoTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        -
          Endpoint: bridgeops@sagebase.org
          Protocol: email
  AWSCWDynmoGetRecordsErrorAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AWSSNSDynamoTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: SystemErrors
      Namespace: AWS/DynamoDB
      Dimensions:
        -
          "Name": "Operation"
          "Value": "GetRecords"
      Period: 900
      Statistic: Maximum
      Threshold: 1
  AWSCWDynamoDashboard:
    Type: 'AWS::CloudWatch::Dashboard'
    Properties:
      DashboardName: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - dashboard
      DashboardBody: !Join
        - ''
        - - >-
            {"widgets": [
            {"type":"metric", "x":0, "y":0, "width":12, "height":6, "properties":
            {"metrics":[
            [ "AWS/DynamoDB", "SystemErrors", "Operation", "GetRecords", {"stat": "Maximum"}]],
            "view": "timeSeries", "stacked": true, "period":300, "stat":"Sum",
            "region":"us-east-1", "title":"DynamoErrors"}}]}
