#This template is used to setup resources for New Relic integrations.
#The resources in this template only need to be created once.
#
#Usage:
#  aws --profile bridge.admin --region us-east-1 \                                                                                                               develop ◼
#  cloudformation create-stack \
#  --stack-name newrelic \
#  --on-failure DELETE \
#  --capabilities CAPABILITY_NAMED_IAM \
#  --template-body file://cf_templates/newrelic.yml
Description: Setup infra resources for New Relic integrations
AWSTemplateFormatVersion: 2010-09-09
Resources:
  AWSIAMNewRelicBudgetPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "NewRelicBudgetPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: "budgets:ViewBudget"
            Resource: "*"
      Roles:
        -
          Ref: AWSIAMNewRelicInfrastructureServiceRole
  AWSIAMNewRelicInfrastructureServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::754728514883:root
            Action:
              - 'sts:AssumeRole'
            Condition:
              StringEquals:
                sts:ExternalId: 1690646
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/ReadOnlyAccess'
